### ISSUE TITLE
On mac, py27, cdat8 and nightly fail when installed from cdat channels

### ISSUE THREAD

**Issue by danlipsa** [CDAT/cdtime#27]
On Mac, py27, both cdat8 and nightly installed using conda channels (not the yaml file) fail with:

(nightly) brasov:src danlipsa$ python t.py 
Traceback (most recent call last):
  File "t.py", line 1, in <module>
    import vcs, cdms2, cdat_info
  File "/Users/danlipsa/projects/vcs/src/vcs/__init__.py", line 102, in <module>
    from .utils import *  # noqa
  File "/Users/danlipsa/projects/vcs/src/vcs/utils.py", line 17, in <module>
    import cdtime
ImportError: dlopen(/Users/danlipsa/anaconda2/envs/nightly/lib/python2.7/site-packages/cdtime.so, 2): Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: /Users/danlipsa/anaconda2/envs/nightly/lib/python2.7/site-packages/cdtime.so
  Reason: Incompatible library version: cdtime.so requires version 52.0.0 or later, but libpng16.16.dylib provides version 51.0.0

Do you know how to fix this? (In the future, adding that pin_run_as_build might help, but its a pity you have to pin to a version to use it)

**Comment by danlipsa** [comment]
After recompiling and installing cdtime in the cdat8 environment I get:
(cdat8) brasov:src danlipsa$ python t.py
Traceback (most recent call last):
  File "t.py", line 1, in <module>
    import vcs, cdms2, cdat_info
  File "/Users/danlipsa/projects/vcs/src/vcs/__init__.py", line 102, in <module>
    from .utils import *  # noqa
  File "/Users/danlipsa/projects/vcs/src/vcs/utils.py", line 20, in <module>
    from . import boxfill
  File "/Users/danlipsa/projects/vcs/src/vcs/boxfill.py", line 20, in <module>
    from . import VCS_validation_functions
  File "/Users/danlipsa/projects/vcs/src/vcs/VCS_validation_functions.py", line 5, in <module>
    import genutil
  File "/Users/danlipsa/anaconda2/envs/cdat8/lib/python2.7/site-packages/genutil/__init__.py", line 5, in <module>
    from .grower import grower  # noqa
  File "/Users/danlipsa/anaconda2/envs/cdat8/lib/python2.7/site-packages/genutil/grower.py", line 3, in <module>
    import cdms2 as cdms
  File "/Users/danlipsa/anaconda2/envs/cdat8/lib/python2.7/site-packages/cdms2/__init__.py", line 26, in <module>
    from .axis import AbstractAxis, axisMatches, axisMatchAxis, axisMatchIndex  # noqa
  File "/Users/danlipsa/anaconda2/envs/cdat8/lib/python2.7/site-packages/cdms2/axis.py", line 23, in <module>
    standard_library.install_aliases()
  File "/Users/danlipsa/anaconda2/envs/cdat8/lib/python2.7/site-packages/future/standard_library/__init__.py", line 483, in install_aliases
    import test
  File "/Users/danlipsa/projects/vcs/src/test.py", line 2, in <module>
AttributeError: 'module' object has no attribute 'init'

**Comment by dnadeau4** [comment]
@danlipsa make sure you don't have a file called "test.py" in your directory.   `standard_library` import test.

**Comment by danlipsa** [comment]
Denis, thanks, I think I passed this renaming the file and also using the install procedure on the website.
