### ISSUE TITLE
year 0 exists

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdtime#38]
```
python -c "import cdtime ; print(cdtime.reltime(-1,'days since 1').tocomp())"
```
0-12-31 0:0:0.0

BUT
```
python -c "import cdtime ; print(cdtime.reltime(-1,'days since 0')"
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/1Tb/miniconda3/envs/jupyter-vcdat/lib/python3.6/site-packages/cdtime/compreltime.py", line 254, in reltime
    return _cdtime.reltime(value, units)
ValueError: Invalid relative time units

**Comment by durack1** [comment]
@doutriaux1 thanks for raising this, I believe I have hit the same problem before..

**Comment by durack1** [comment]
@jasonb5 this is similar in some ways to #46, and I know that @pochedls has suggested a work around for the issue (so rather than a traceback as above, it works) in https://github.com/CDAT/cdms/issues/334

**Comment by jasonb5** [comment]
I need to look at the code to get an idea of what changes are required. 

I see two viable options going forward:
1. Modify libcdms to support year 0 and display a warning message.
2. Add a flag to cdtime conversion methods to handle this case.
